# Generated by Django 5.2.12 on 2026-09-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_id', models.CharField(max_length=50, unique=True)),
                ('driver_name', models.CharField(max_length=150)),
                ('starting_place', models.CharField(default='Campus', max_length=150)),
                ('ending_place', models.CharField(max_length=150)),
                ('route', models.CharField(max_length=150)),
                ('drivers_contact_number', models.CharField(max_length=20)),
                ('capacity', models.CharField(default='50', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Maintenance', 'Maintenance')], default='Active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_id', models.CharField(max_length=50, unique=True)),
                ('latitude', models.FloatField(default=10.2315)),
                ('longitude', models.FloatField(default=76.415)),
                ('speed', models.FloatField(default=0.0)),
                ('status', models.CharField(default='On Route', max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeatBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_roll_no', models.CharField(max_length=50)),
                ('student_name', models.CharField(blank=True, default='', max_length=150)),
                ('bus_number', models.CharField(max_length=50)),
                ('seat_number', models.CharField(max_length=20)),
                ('booking_date', models.CharField(max_length=50)),
                ('trip_time', models.CharField(max_length=100)),
                ('status', models.CharField(default='Confirmed', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=128)),
                ('designation', models.CharField(default='Driver', max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('experience', models.CharField(default='1 Year', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=150)),
                ('roll_no', models.CharField(max_length=50, unique=True)),
                ('route', models.CharField(max_length=150)),
                ('stop', models.CharField(max_length=150)),
                ('bus_number', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TravelReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=50, unique=True)),
                ('bus_number', models.CharField(max_length=50)),
                ('route', models.CharField(max_length=150)),
                ('driver', models.CharField(max_length=150)),
                ('arrival_time', models.CharField(max_length=50)),
                ('departure_time', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('On Time', 'On Time'), ('Delayed', 'Delayed')], default='On Time', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
