# Generated by Django 5.2.12 on 2026-09-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_loginhistory_staff_login_count_student_login_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLoginCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('staff', 'Staff'), ('admin', 'Admin')], max_length=20)),
                ('user_id', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('login_count', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Daily Login Counts',
                'unique_together': {('user_type', 'user_id', 'date')},
            },
        ),
    ]
